### ISSUE TITLE
Does this library fit for Global Platform 2.2?

### ISSUE THREAD

**Issue by bakhodir1986** [jamesharling/GlobalPlatform.NET#1]
Does this library fit for Global Platform 2.2?
How to open Code  with VS 2015?

**Comment by jamesharling** [comment]
It should work on GP 2.2 cards yeah. I'm mainly using it on JCOP cards that implement the 2.1.1 spec and the majority of commands are supported; ultimately though, it depends on the OS on the card and how much of the spec it implements. Give it a try!

FYI, secure channel support should be available in this library in a few weeks.

**Comment by bakhodir1986** [comment]
You have added secure channel protocol
Thank you very much!!!

**Comment by jamesharling** [comment]
Still a work in progress, need to do some more testing on it. Any feedback is appreciated though! What secure channel options are you hoping to use?

**Comment by bakhodir1986** [comment]
Very good. Scp02. I want to use

Отправлено из Почты для Windows 10

От: James Harling
Отправлено: 14 августа 2017 г. в 0:17
Кому: jamesharling/GlobalPlatform.NET
Копия: bakhodir1986; Author
Тема: Re: [jamesharling/GlobalPlatform.NET] Does this library fit forGlobal Platform 2.2? (#1)

Still a work in progress, need to do some more testing on it. Any feedback is appreciated though! What secure channel options are you hoping to use?

**Comment by jamesharling** [comment]
Do you know if it's SCP02 Option 15 (i15) or Option 55 (i55)? The library supports just i15 at the moment.
