### ISSUE TITLE
SecureChannelSession

### ISSUE THREAD

**Issue by rdmendesp** [jamesharling/GlobalPlatform.NET#11]
SecureApdu: if my APDU has a response different sw:9000 i think you couldn´t change the cmac:

this.CMac = mac;

All other commands will fail after this...

**Comment by jamesharling** [comment]
Historically this has always been OK for me. Say I malform a command going to the card and get a response like `6A 88` (data not found) - the next command going to the card should be using the previous command's MAC as the ICV for its MAC.

Are you getting problems at the moment?
