### ISSUE TITLE
ByteExtensions

### ISSUE THREAD

**Issue by rdmendesp** [jamesharling/GlobalPlatform.NET#13]
Pad function is missing the if below, whitout this give error when block has 8 bytes... SW: 6982

      public static IList<byte> Pad(this IList<byte> bytes)
      {
         bytes.Add(0x80);
         
         **if (bytes.Count % 8 != 0)**
            bytes.AddRange(Enumerable.Repeat<byte>(0x00, 8 - bytes.Count % 8));

         return bytes;
      }

I was going crazy with this problem... lol...

**Comment by jamesharling** [comment]
Do you think this is causing the problems you were having in #11?

**Comment by rdmendesp** [comment]
Maybe... I am doing more tests...
