### ISSUE TITLE
InstallCommand

### ISSUE THREAD

**Issue by rdmendesp** [jamesharling/GlobalPlatform.NET#14]
Set ForMakeSelectable and ForInstall at the same command...

**Comment by jamesharling** [comment]
Can you elaborate on the issue?

**Comment by rdmendesp** [comment]
I want send the apdu with P1 = 0xC0, "For install"and "For make selectable"

**Comment by jamesharling** [comment]
It is currently possible for the `InstallCommand` builder to generate a number of commands for a combined process. You must generate the ForLoad command first, and at the point of calling `AsApdu()` you'll see you can call `ForInstall()`. Likewise, after this you can call `ForMakeSelectable()`. After building your combined process you can call `AsApdus()` (notice the plural) which will create a number of APDUs for you.

Personally I've not dealt much with combined commands however, so it sounds like I might need to do some work here! I will do some research and look at a feature release soon.

**Comment by jamesharling** [comment]
Code complete, and commited to the `develop` branch. Waiting on release 1.3.0.
