### ISSUE TITLE
Message Data Confidentiality 

### ISSUE THREAD

**Issue by rdmendesp** [jamesharling/GlobalPlatform.NET#15]
Can i send a apdu with "Message Data Confidentiality" with this framework?

**Comment by jamesharling** [comment]
I believe you are referring to the encryption of the command data field when authenticating and communicating with the card? If so, absolutely. Simply set up your secure channel session and corresponding `EXTERNAL AUTHENTICATE` command using `SecurityLevel.CDecryption`:

https://github.com/jamesharling/GlobalPlatform.NET/blob/33343f0afaf836e9136feeac7ee449b333931264/src/GlobalPlatform.NET/SecureChannel/SCP02/Reference/SecurityLevel.cs#L8

The secure channel session object will then secure any outgoing APDUs using both MACing (b8 = 1) and message data encryption (b7 = 1).

**Comment by rdmendesp** [comment]
I try this... so sucess ... sw 69 82

SELECT A999999999991010 [A999999999991010]
   -> [00 A4 04 00 08 A9 99 99 99 99 99 10 10 00]
   <- [90 00] 

INITIALIZE UPDATE
   -> [80 50 00 00 08 37 80 A7 1F 74 AA 5F 3A 00]
   <- [00 00 02 49 02 64 75 08 38 21 FF 02 00 60 DF 07 94 F7 31 7B 92 64 8E 3A 97 08 C2 97 90 00] 
   Key diversification data: 00000249026475083821
   Key information: FF02
   Card challenge: 0060DF0794F7317B
   Card cryptogram: 92648E3A9708C297

EXTERNAL AUTHENTICATE
   -> [84 82 01 00 10 E7 EB 4B 25 0B 9E 7A 1D 70 94 3C 0A B6 48 9B 6E 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 00 37 01 01 2C 70 2A 61 28 4F 07 A0 00 00 00 03 10 10 50 0A 56 49 53 41 43 52 45 44 49 54 87 01 01 9F 12 0D 43 52 45 44 49 54 4F 44 45 56 49 53 41 48 EC C7 CD 4C 89 53 DC 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 01 4B 01 01 40 70 3E 5F 20 0F 46 55 4C 4C 20 46 55 4E 43 54 49 4F 4E 41 4C 57 11 47 61 73 90 01 01 00 10 D2 01 22 01 01 23 45 67 89 9F 1F 16 30 31 30 32 30 33 30 34 30 35 30 36 30 37 30 38 30 39 30 41 30 42 D5 56 AE D3 AF 63 F3 3A 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 02 1B 02 01 10 70 0E 5A 08 47 61 73 90 01 01 00 10 5F 34 01 01 82 ED 6B 69 52 DA 90 52 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 03 59 02 02 4E 70 4C 8C 17 95 05 9B 02 9F 02 06 9F 03 06 9F 1A 02 5F 2A 02 9A 03 9C 01 9F 37 04 8D 19 95 05 9B 02 8A 02 9F 02 06 9F 03 06 9F 1A 02 5F 2A 02 9A 03 9C 01 9F 37 04 9F 0E 05 00 50 08 00 00 9F 0F 05 F0 20 04 98 00 9F 0D 05 F0 20 04 00 00 8C AC C4 9E 4D 8A 83 FF 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 04 40 02 03 35 70 33 5F 25 03 95 07 01 5F 24 03 20 12 31 5F 28 02 08 40 9F 07 02 FF C0 8E 0C 00 00 00 00 00 00 00 00 5F 03 00 00 9F 08 02 00 8C 5F 30 02 02 01 9F 42 02 08 40 80 1A AB 04 79 5B B6 DA 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 05 72 03 01 67 70 65 8F 01 57 90 60 56 69 91 43 20 B9 6C B5 44 25 EF 78 41 C8 75 C7 67 DD 82 B3 5F E5 C1 35 2B A2 8D 15 C1 AC 99 F7 A6 8D 38 D9 DC 25 F5 6E 4A 76 E8 EF 79 65 C6 28 EB F0 83 45 5B 68 0E 62 AE 98 ED 24 A0 80 4A 7A 76 C5 98 98 25 77 2B 22 5B B7 EE A5 7D 20 4C C6 70 39 D4 50 12 B8 FB A3 13 E5 5A 48 7B BA CC C1 83 30 6F 1E 5E 82 B2 4A 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 06 27 03 02 1C 70 1A 9F 32 01 03 92 14 CF B8 D4 88 5D 96 09 67 17 9F 98 2D 42 CE 54 EC C2 05 46 83 4B 88 8B 57 CA D8 62 9B 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 07 5F 03 03 54 70 52 93 50 11 0B B9 DF 2D 21 98 19 06 B2 9A 30 14 11 F9 FA 60 CF 49 4D BA BA BF 54 B1 79 7C 9C 4B 5D 99 B5 E6 7A B7 30 49 E7 71 FC 5F DC 23 E5 83 50 B7 81 00 53 24 D3 1D C8 7A D0 FB F6 36 73 38 08 05 6D 66 07 46 32 71 1E 7C BF 14 07 37 96 E1 B6 0D 4D 16 34 C8 52 B2 FA 51 3B 00]
   <- [90 00] 

STORE DATA
   -> [84 E2 00 08 40 A2 71 5D 1A CB 8E C2 EA F0 78 3A FB 22 61 44 DA F1 01 C3 75 FE EA 1F 0E 1F BB 57 1B DE 79 FB 2A 0A 63 25 DD 6D 3D 18 2D CA AC 96 EE 1C 56 9C 07 55 A1 E0 26 F4 0E 8C 0C 3A EE B6 CA 0E F0 A1 22 00]
   <- [69 82] SECSTATNOTSAT

**Comment by jamesharling** [comment]
Possible bug due to #13

**Comment by jamesharling** [comment]
Please try release 1.2.1 and see if your problem persists.
