### ISSUE TITLE
The package fails to install

### ISSUE THREAD

**Issue by Kmortimer** [jamesharling/GlobalPlatform.NET#23]
Tried with many .Net version it fails to install
Could not install package 'GlobalPlatform.NET 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Install-Package : Could not install package 'GlobalPlatform.NET 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but 
the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jamesharling** [comment]
This library is compiled against .NET Standard 2.0, so to consume it you'll need to use .NET Core 2.0+, or .NET Framework 4.6.1+ with the .NET Core 2.0 SDK. Have a look at this matrix: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support
