### ISSUE TITLE
Could you explane me how you generate MAC value for EXTERNAL AUTHENTICATE?

### ISSUE THREAD

**Issue by bakhodir1986** [jamesharling/GlobalPlatform.NET#3]
When I use EXTERNAL AUTHENTICATE for GP 2.2 MAC generation by your library make difference result

**Comment by jamesharling** [comment]
I've just released a new version, 1.1.1, with a huge number of bugfixes and changes. Please update your package and let me know if you still have problems. I've also updated the README to include a guide on using secure channel sessions.

**Comment by jamesharling** [comment]
In fact, try 1.1.2 - I noticed a bug in MAC calculation.

**Comment by bakhodir1986** [comment]
OK Thank you

Отправлено из Почты для Windows 10

От: James Harling
Отправлено: 19 августа 2017 г. в 17:54
Кому: jamesharling/GlobalPlatform.NET
Копия: bakhodir1986; Author
Тема: Re: [jamesharling/GlobalPlatform.NET] Could you explane me how yougenerate MAC value for EXTERNAL AUTHENTICATE? (#3)

In fact, try 1.1.2 - I noticed a bug in MAC calculation.

**Comment by bakhodir1986** [comment]
MAC is renerating well
