### ISSUE TITLE
GetStatusCommand

### ISSUE THREAD

**Issue by rdmendesp** [jamesharling/GlobalPlatform.NET#7]
Is missing p2 parameters...

**Comment by jamesharling** [comment]
What `DataObject` were you passing in and what did you expect the resulting APDU to be?

**Comment by rdmendesp** [comment]
I want set the "Response data structure"... And when the response has more occurrences (SW: 6310) i need set the "Get next occurrence(s)"

**Comment by jamesharling** [comment]
Could you tell me which section of the GlobalPlatform 2.3 specification your requirements are in?

**Comment by rdmendesp** [comment]
Table 11-34: GET STATUS Reference Control Parameter P2

![image](https://user-images.githubusercontent.com/31245031/29579445-436b493a-8749-11e7-8456-3cfc1f337e47.png)

**Comment by jamesharling** [comment]
Thanks, I was confused as the title was originally about `GET DATA`!
